# Generated by Django 3.2.8 on 2021-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('emailId', models.EmailField(max_length=254)),
                ('mobileNo', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=500)),
                ('address', models.TextField()),
            ],
        ),
    ]
